"""
Database Service Module
========================
Provides a MongoDB persistence layer for Digital Replicas and Digital Twins.

Architecture reasoning (from the lecture):
- This service encapsulates ALL database interactions (connect, CRUD for DRs).
- It delegates schema validation to the SchemaRegistry so that the DB layer
  remains type-agnostic: adding a new DR type only requires a new YAML template
  — no changes in this file.
- Collection names are derived automatically via the SchemaRegistry
  (`<dr_type>_collection`), keeping the mapping consistent.
- The service stores a reference to the SchemaRegistry at init time so that
  save/get/query/update/delete operations can look up the correct collection
  and validation rules without any DR-type-specific logic.
"""

from typing import Dict, List, Optional
from pymongo import MongoClient
from datetime import datetime
from cloud_platform.virtualization.digital_replica.schema_registry import SchemaRegistry


class DatabaseService:
    """
    MongoDB wrapper used by the DT Factory and the application APIs.

    Lifecycle:
        1. Instantiate with connection string, db name, and a populated SchemaRegistry.
        2. Call connect() once at startup.
        3. Use save_dr / get_dr / query_drs / update_dr / delete_dr throughout.
        4. Call disconnect() on shutdown.
    """

    def __init__(self, connection_string: str, db_name: str, schema_registry: SchemaRegistry):
        self.connection_string = connection_string
        self.db_name = db_name
        self.schema_registry = schema_registry
        # MongoClient and Database references — populated by connect()
        self.client = None
        self.db = None

    # ── Connection management ─────────────────────────────────────────

    def connect(self) -> None:
        """
        Open a connection to MongoDB and select the target database.

        Raises:
            ConnectionError: If the client cannot reach the MongoDB server.
        """
        try:
            self.client = MongoClient(self.connection_string)
            self.db = self.client[self.db_name]
        except Exception as e:
            raise ConnectionError(f"Failed to connect to MongoDB: {str(e)}")

    def disconnect(self) -> None:
        """Gracefully close the MongoDB connection."""
        if self.client:
            self.client.close()
            self.client = None
            self.db = None

    def is_connected(self) -> bool:
        """Check whether the client is currently connected."""
        return self.client is not None and self.db is not None

    # ── CRUD for Digital Replicas ─────────────────────────────────────

    def save_history_event(self, history_event: Dict) -> None:
        '''
        Save the history event in the database.
        Args:
            history_event: The full history event document dict - generated by the HistoryFactory.
        '''
        if not self.is_connected():
            raise ConnectionError("Not connected to MongoDB")

        collection_name = self.schema_registry.get_collection_name("history") # -> 'history_collection'
        collection = self.db[collection_name]
        collection.insert_one(history_event)
    

    def save_history_events(self, event_data: List[Dict]):
        """
        Specialized method to persist multiple history events with uniqueness constraint on 'timestamp'.

        Args:
            event_data: A list of full event document dicts - history_data generated by the DRFactory.

        Returns:
            The list of rejected events for logging/debugging.
        """
        ## EXPLANATION:
        #  I'm going to use this function with this idea, every time I receive a new list of readings containing multiple events related to multiple devices,
        #  I'll separate the list by device_id and then for each device, I'll call this function to save the history events.
        

        # Check connection before attempting to save
        if not self.is_connected():
            raise ConnectionError("Not connected to MongoDB")
        unique = []  # Track timestamps to enforce uniqueness
        collection_name = self.schema_registry.get_collection_name("history") # -> 'history_collection'
        collection = self.db[collection_name]
        rejected_events = {}  # Track rejected events for logging/debugging
        for event in event_data:
            try:
                # check if an event with the same device_id and timestamp already exists in the collection
                if collection.find_one({
                    "device_id": event.get("device_id"),
                    "timestamp": event.get("timestamp")}):

                    rejected_events[event.get("device_id")] = f"timestamp {event.get('timestamp')} already exists"
                    continue  # Skip this event and continue with the next one
                unique.append(event)
            except Exception as e:
                raise Exception(f"Failed to save history event: {str(e)}")
            
        collection.insert_many(unique)
        return rejected_events  # Return rejected events for logging/debugging
        
    def add_dr(self, dr_entry: Dict) -> Dict:
        """
        Insert a new Digital Replica document in the specified collection.

        Args:
            dr_entry: The full DR document dict - generated by the DRFactory.

        Returns:
            The digital replica document with the generated ID.
        """

        # Check connection before attempting to save
        if not self.is_connected():
            raise ConnectionError("Not connected to MongoDB")

        # having received the DR data, we can look up the collection name from the schema registry perform validation and then save the document to the correct collection.  
        # This keeps the DB layer generic and decoupled from specific DR types.
        collection_name = self.schema_registry.get_collection_name(dr_entry.get("dr_type", "device")) # default to "device" collection if type is missing
        collection = self.db[collection_name]
        try:
            # When pymongo inserts a document, it actually 
            #   **IMPORTANT**  modifies the dr_data dictionary in-place  **IMPORTANT**
            # by adding the _id key to it. So, after insert_one executes, 
            # dr_data will be the full digital replica including its generated database _id.
            collection.insert_one(dr_entry) 
            return dr_entry

        except Exception as e:
            raise Exception(f"Failed to save Digital Replica: {str(e)}")
        
# # 1. update the device in the devices collection (enforce uniqueness on 'name' field)
#             existing = collection.find_one({"device_id": dr_data.get("device_id")})
#             if existing:
#                 # Update the existing device document
#                 collection.update_one({"_id": existing["_id"]}, {"$set": dr_data})
#                 return str(existing["_id"])
#             else: # Insert a new device document
#                 collection.insert_one(dr_data)
#                 return str(dr_data["_id"])
            
    def get_dr(self, dr_type: str, dr_id: str) -> Optional[Dict]:
        """
        Retrieve a single DR by type and _id.

        Returns:
            The DR document dict, or None if not found.
        """
        if not self.is_connected():
            raise ConnectionError("Not connected to MongoDB")

        try:
            collection_name = self.schema_registry.get_collection_name(dr_type)
            return self.db[collection_name].find_one({"_id": dr_id})
        except Exception as e:
            raise Exception(f"Failed to get Digital Replica: {str(e)}")

    def query_drs(self, dr_type: str, query: Dict | None = None) -> List[Dict]:
        """
        Query DRs of a given type with an optional MongoDB filter.

        Args:
            dr_type: DR type key.
            query:   Optional MongoDB query dict.  Pass {} or None for all.

        Returns:
            A list of matching DR document dicts.
        """
        if not self.is_connected():
            raise ConnectionError("Not connected to MongoDB")

        try:
            collection_name = self.schema_registry.get_collection_name(dr_type)
            return list(self.db[collection_name].find(query or {}))
        except Exception as e:
            raise Exception(f"Failed to query Digital Replicas: {str(e)}")

    def update_dr(self, collection_name: str = "device", dr_id: str, update_data: Dict) -> None:
        """
        Partially update a DR document using MongoDB $set.

        The metadata.updated_at timestamp is always refreshed automatically.

        Args:
            collection_name: The name of the MongoDB collection.
            dr_id:       The _id of the DR to update.
            update_data: Dict of fields to set (can be nested).

        Raises:
            ValueError: If no document matched the given dr_id.
        """
        if not self.is_connected():
            raise ConnectionError("Not connected to MongoDB")

        try:
            collection_name = self.schema_registry.get_collection_name(collection_name)

            # Always bump the updated_at timestamp
            if "metadata" not in update_data:
                update_data["metadata"] = {}
            update_data["metadata"]["updated_at"] = datetime.utcnow()

            result = self.db[collection_name].update_one(
                {"_id": dr_id},
                {"$set": update_data}
            )

            if result.matched_count == 0:
                raise ValueError(f"Digital Replica not found: {dr_id}")
        except Exception as e:
            raise Exception(f"Failed to update Digital Replica: {str(e)}")

    def delete_dr(self, dr_type: str, dr_id: str) -> None:
        """
        Delete a DR document by type and id.

        Raises:
            ValueError: If no document matched the given dr_id.
        """
        if not self.is_connected():
            raise ConnectionError("Not connected to MongoDB")

        try:
            collection_name = self.schema_registry.get_collection_name(dr_type)
            result = self.db[collection_name].delete_one({"_id": dr_id})

            if result.deleted_count == 0:
                raise ValueError(f"Digital Replica not found: {dr_id}")
        except Exception as e:
            raise Exception(f"Failed to delete Digital Replica: {str(e)}")
