"""
Database Service Module
========================
Provides a MongoDB persistence layer for Digital Replicas and Digital Twins.

Architecture reasoning (from the lecture):
- This service encapsulates ALL database interactions (connect, CRUD for DRs).
- It delegates schema validation to the SchemaRegistry so that the DB layer
  remains type-agnostic: adding a new DR type only requires a new YAML template
  — no changes in this file.
- Collection names are derived automatically via the SchemaRegistry
  (`<dr_type>_collection`), keeping the mapping consistent.
- The service stores a reference to the SchemaRegistry at init time so that
  save/get/query/update/delete operations can look up the correct collection
  and validation rules without any DR-type-specific logic.
"""

from typing import Dict, List, Optional
from pymongo import MongoClient
from pymongo.database import Database
from datetime import datetime
from cloud_platform.virtualization.digital_replica.schema_registry import SchemaRegistry
import logging

logger = logging.getLogger(__name__)

class DatabaseService:
    """
    MongoDB wrapper used by the DT Factory and the application APIs.

    Lifecycle:
        1. Instantiate with connection string, db name, and a populated SchemaRegistry.
        2. Call connect() once at startup.
        3. Use save_dr / get_dr / query_drs / update_dr / delete_dr throughout.
        4. Call disconnect() on shutdown.
    """

    def __init__(self, connection_string: str, db_name: str, schema_registry: SchemaRegistry):
        self.connection_string = connection_string
        self.db_name = db_name
        self.schema_registry = schema_registry
        # MongoClient and Database references — populated by connect()
        self.client: Optional[MongoClient] = None
        self.db: Optional[Database] = None
        

    # ── Connection management ─────────────────────────────────────────

    def connect(self) -> None:
        """
        Open a connection to MongoDB and select the target database.

        If the service is already connected, this method becomes a no-op.

        Raises:
            ConnectionError: If the client cannot reach the MongoDB server.
        """
        if self.is_connected():
            return

        try:
            self.client = MongoClient(self.connection_string)
            self.db = self.client[self.db_name]
        except Exception as e:
            raise ConnectionError(f"Failed to connect to MongoDB: {str(e)}")

    def disconnect(self) -> None:
        """Gracefully close the MongoDB connection."""
        if self.client:
            self.client.close()
            self.client = None
            self.db = None

    def is_connected(self) -> bool:
        """Check whether the client is currently connected."""
        return self.client is not None and self.db is not None

    @staticmethod
    def _ensure_id(document: Dict, label: str) -> None:
        if not document or document.get("_id") in (None, ""):
            raise ValueError(f"{label} must include _id")

    # ── CRUD for Digital Replicas ─────────────────────────────────────

    def save_history_event(self, history_event: Dict) -> None:
        '''
        Save the history event in the database.
        Args:
            history_event: The full history event document dict - generated by the HistoryFactory.
        '''
        if not self.is_connected():
            raise ConnectionError("Not connected to MongoDB")

        assert isinstance(self.db, Optional[Database])

        if not history_event.get("_id"):
            raise ValueError("History event must include _id (generated by HistoryFactory)")

        self._ensure_id(history_event, "History event")

        collection_name = self.schema_registry.get_collection_name("history") # -> 'history_collection'
        collection = self.db[collection_name]
        collection.insert_one(history_event)
    

    def save_history_events(self, event_data: List[Dict]):
        """
        Specialized method to persist multiple history events with uniqueness constraint on 'timestamp'.

        Args:
            event_data: A list of full event document dicts - history_data generated by the DRFactory.

        Returns:
            The list of rejected events for logging/debugging.
        """
        ## EXPLANATION:
        #  I'm going to use this function with this idea, every time I receive a new list of readings containing multiple events related to multiple devices,
        #  I'll separate the list by device_id and then for each device, I'll call this function to save the history events.
        

        # Check connection before attempting to save
        if not self.is_connected():
            raise ConnectionError("Not connected to MongoDB")
        unique = []  # Track timestamps to enforce uniqueness
        collection_name = self.schema_registry.get_collection_name("history") # -> 'history_collection'
        collection = self.db[collection_name]
        rejected_events = {}  # Track rejected events for logging/debugging
        for event in event_data:
            try:
                if not event.get("_id"):
                    rejected_events[event.get("device_id", "unknown")] = "missing _id"
                    continue
                self._ensure_id(event, "History event")
                unique.append(event)
            except Exception as e:
                raise Exception(f"Failed to save history event: {str(e)}")
            
        collection.insert_many(unique)
        return rejected_events  # Return rejected events for logging/debugging
        
    def add_dr(self, dr_entry: Dict) -> Dict:
        """
        Insert a new Digital Replica document in the specified collection.

        Args:
            dr_entry: The full DR document dict - generated by the DRFactory.

        Returns:
            The digital replica document with the generated ID.
        """

        # Check connection before attempting to save
        if not self.is_connected():
            raise ConnectionError("Not connected to MongoDB")

        if not dr_entry.get("_id"):
            raise ValueError("Digital Replica must include _id (generated by DRFactory)")

        if not dr_entry.get("_id"):
            raise ValueError("Digital Replica must include _id (generated by DRFactory)")

        self._ensure_id(dr_entry, "Digital Replica")

        # having received the DR data, we can look up the collection name from the schema registry perform validation and then save the document to the correct collection.  
        # This keeps the DB layer generic and decoupled from specific DR types.
        collection_name = self.schema_registry.get_collection_name(dr_entry.get("dr_type", "device")) # default to "device" collection if type is missing
        collection = self.db[collection_name]
        try:
            # Pymongo inserts the document as-is; _id must be provided by the factory.
            collection.insert_one(dr_entry) 
            return dr_entry

        except Exception as e:
            raise Exception(f"Failed to save Digital Replica: {str(e)}")
        
# # 1. update the device in the devices collection (enforce uniqueness on 'name' field)
#             existing = collection.find_one({"device_id": dr_data.get("device_id")})
#             if existing:
#                 # Update the existing device document
#                 collection.update_one({"_id": existing["_id"]}, {"$set": dr_data})
#                 return str(existing["_id"])
#             else: # Insert a new device document
#                 collection.insert_one(dr_data)
#                 return str(dr_data["_id"])
            
    def get_dr(self, dr_type: str, dr_id: str) -> Optional[Dict]:
        """
        Retrieve a single DR by type and _id.

        Returns:
            The DR document dict, or None if not found.
        """
        if not self.is_connected():
            raise ConnectionError("Not connected to MongoDB")

        try:
            collection_name = self.schema_registry.get_collection_name(dr_type)
            return self.db[collection_name].find_one({"_id": dr_id})
        except Exception as e:
            raise Exception(f"Failed to get Digital Replica: {str(e)}")

    def query_drs(self, dr_type: str, query: Dict | None = None) -> List[Dict]:
        """
        Query DRs of a given type with an optional MongoDB filter.

        Args:
            dr_type: DR type key.
            query:   Optional MongoDB query dict.  Pass {} or None for all.

        Returns:
            A list of matching DR document dicts.
        """
        if not self.is_connected():
            raise ConnectionError("Not connected to MongoDB")

        try:
            collection_name = self.schema_registry.get_collection_name(dr_type)
            return list(self.db[collection_name].find(query or {}))
        except Exception as e:
            raise Exception(f"Failed to query Digital Replicas: {str(e)}")

    def query_history_records(self, query: Dict | None = None, limit: int | None = None) -> List[Dict]:
        """
        Query the latest history records using a Mongo-style filter.

        Args:
            query: MongoDB filter dictionary, for example {"device_id": "sensor-1"}.
            limit: Maximum number of records to return.

        Returns:
            A list of matching history documents ordered from newest to oldest.
        """
        if not self.is_connected():
            raise ConnectionError("Not connected to MongoDB")

        if isinstance(query, str):
            logger.info("receiced query")
            query = {"device_id": query}
        elif query is None:
            query = {}
        elif not isinstance(query, dict):
            raise TypeError("query must be a dict or a device_id string")

        try:
            collection_name = self.schema_registry.get_collection_name("history")
            logger.info(f"querying this: {query}")
            if isinstance(limit, int) and limit > 0:
                cursor = (
                    self.db[collection_name]
                    .find(query)
                    .sort("timestamp", -1)
                    .limit(limit)
                )
            else:
                cursor = (
                    self.db[collection_name]
                    .find(query)
                    .sort("timestamp", -1)
                )
            return list(cursor)
        except Exception as e:
            raise Exception(f"Failed to query history records: {str(e)}")

    @staticmethod
    def _flatten_for_set(d: Dict, prefix: str = "") -> Dict:
        """
        Flatten a nested dict into dot-notation keys for MongoDB $set.

        Using ``$set`` with a nested dict (e.g. ``{"data": {"value": 1}}``) would
        **replace the entire ``data`` subdocument**, wiping all sibling fields that
        were written at creation time.  Flattening to dot-notation
        (e.g. ``{"data.value": 1}``) instructs MongoDB to update only the
        specified leaf fields, leaving every other field untouched.

        Only plain dicts are recursed into; lists and scalars are kept as-is so
        that whole arrays are replaced atomically (not element-by-element).

        Example::

            {"data": {"value": 96.52, "timestamp": "..."}, "metadata": {"updated_at": <dt>}}
            → {"data.value": 96.52, "data.timestamp": "...", "metadata.updated_at": <dt>}
        """
        result = {}
        for k, v in d.items():
            full_key = f"{prefix}.{k}" if prefix else k
            if isinstance(v, dict):
                result.update(DatabaseService._flatten_for_set(v, full_key))
            else:
                result[full_key] = v
        return result

    def update_dr(self, collection_name: str, dr_id: str, update_data: Dict) -> None:
        """
        Partially update a DR document using MongoDB $set.

        Nested dicts in update_data are flattened to dot-notation keys so that
        only the specified sub-fields are touched (instead of replacing the
        whole subdocument).

        Args:
            collection_name: The DR type or collection key (resolved via SchemaRegistry).
            dr_id:           The _id of the DR to update.
            update_data:     Dict of fields to set (may be nested).

        Raises:
            ValueError: If no document matched the given dr_id.
        """
        if not self.is_connected():
            raise ConnectionError("Not connected to MongoDB")

        try:
            collection_name = self.schema_registry.get_collection_name(collection_name)

            # Flatten nested dicts → dot-notation so $set only touches leaf fields
            flat_update = self._flatten_for_set(update_data)

            result = self.db[collection_name].update_one(
                {"_id": dr_id},
                {"$set": flat_update}
            )
        except Exception as e:
            raise Exception(f"Failed to update Digital Replica: {str(e)}")

    def delete_dr(self, dr_type: str, dr_id: str) -> None:
        """
        Delete a DR document by type and id.

        Raises:
            ValueError: If no document matched the given dr_id.
        """
        if not self.is_connected():
            raise ConnectionError("Not connected to MongoDB")

        try:
            collection_name = self.schema_registry.get_collection_name(dr_type)
            result = self.db[collection_name].delete_one({"_id": dr_id})

            if result.deleted_count == 0:
                raise ValueError(f"Digital Replica not found: {dr_id}")
        except Exception as e:
            raise Exception(f"Failed to delete Digital Replica: {str(e)}")
